// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'kvpair_test.dart' as prefix1;
import 'package:reflected_mustache/mustache.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.MustacheMirrorsUsedAnnotation(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"MyKVPair",
            r"test.unit.keyvalue.MyKVPair",
            7,
            0,
            const prefix0.MustacheMirrorsUsedAnnotation(),
            const <int>[0, 1, 4],
            const <int>[5, 6, 7, 8, 9, 2, 3],
            const <int>[],
            -1,
            {},
            {},
            {
              r"": (b) =>
                  (key, value) => b ? new prefix1.MyKVPair(key, value) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(r"key", 33797, 0,
            const prefix0.MustacheMirrorsUsedAnnotation(), -1, 1, 1, null),
        new r.VariableMirrorImpl(
            r"value",
            17413,
            0,
            const prefix0.MustacheMirrorsUsedAnnotation(),
            null,
            null,
            null,
            null),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.MustacheMirrorsUsedAnnotation(), 0, 1, 1, 2),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.MustacheMirrorsUsedAnnotation(), 1, null, null, 3),
        new r.MethodMirrorImpl(r"", 0, 0, -1, 0, 0, const <int>[0, 1],
            const prefix0.MustacheMirrorsUsedAnnotation(), null),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, 2, 2, const <int>[2],
            const prefix0.MustacheMirrorsUsedAnnotation(), null),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, 1, 1,
            const <int>[], const prefix0.MustacheMirrorsUsedAnnotation(), null),
        new r.MethodMirrorImpl(
            r"noSuchMethod",
            65538,
            null,
            null,
            null,
            null,
            const <int>[3],
            const prefix0.MustacheMirrorsUsedAnnotation(),
            null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, 3, 3,
            const <int>[], const prefix0.MustacheMirrorsUsedAnnotation(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, 4, 4,
            const <int>[], const prefix0.MustacheMirrorsUsedAnnotation(), null)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(
            r"key",
            32774,
            4,
            const prefix0.MustacheMirrorsUsedAnnotation(),
            -1,
            1,
            1,
            null,
            null,
            null),
        new r.ParameterMirrorImpl(
            r"value",
            16390,
            4,
            const prefix0.MustacheMirrorsUsedAnnotation(),
            null,
            null,
            null,
            null,
            null,
            null),
        new r.ParameterMirrorImpl(
            r"other",
            16390,
            5,
            const prefix0.MustacheMirrorsUsedAnnotation(),
            null,
            null,
            null,
            null,
            null,
            null),
        new r.ParameterMirrorImpl(
            r"invocation",
            32774,
            7,
            const prefix0.MustacheMirrorsUsedAnnotation(),
            -1,
            5,
            5,
            null,
            null,
            null)
      ],
      <Type>[prefix1.MyKVPair, String, bool, int, Type, Invocation],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"key": (dynamic instance) => instance.key,
        r"value": (dynamic instance) => instance.value
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
