# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      reflectable:
        generate_for:
          exclude:
          - example/**.dart
          - lib/**.dart
        options:
          formatted: true
