name: relected_mustache
version: 0.1.0

author: Mike Mitterer <office@mikemitterer.at>
description: Mustache template library
homepage: https://github.com/MikeMitterer/relected_mustache

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  reflectable: #^2.0.0
    path: /Volumes/Daten/DevLocal/DevDart/reflectable

dev_dependencies:
  test: any

  build_runner: ^0.8.10
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
                     